### ISSUE TITLE
Mods are not working

### ISSUE THREAD

**Issue by ghost** [yeet-zone/docker-dontstarvetogether#79]
Hi there.
I tried to set up a docker container with mods enabled. Therefor I used the exactly same files like in [your examples directory](https://github.com/dst-academy/docker-dontstarvetogether/tree/develop/docs/examples/mods). Unfortunately the mods won't be installed or enabled.

Here's my log:
```
[00:00:00]: PersistRootStorage is now /var/lib/dsta//./cluster/shard/ 
[00:00:00]: Starting Up
[00:00:00]: Version: 194420
[00:00:00]: Current time: Tue Nov  1 08:21:33 2016

[00:00:00]: System Name: Linux
[00:00:00]: Host Name: dst
[00:00:00]: Release(Kernel) Version: 4.4.0-36-generic
[00:00:00]: Kernel Build Timestamp: #55-Ubuntu SMP Thu Aug 11 18:01:55 UTC 2016
[00:00:00]: Machine Arch: x86_64
[00:00:00]: Don't Starve Together: 194420 LINUX
[00:00:00]: Build Date: 1378
[00:00:00]: Parsing command line
[00:00:00]: Command Line Arguments: -persistent_storage_root /var/lib/dsta -conf_dir . -cluster cluster -shard shard -backup_log_count 0 
[00:00:00]: Initializing distribution platform
[00:00:00]: ....Done
[00:00:00]: THREAD - started 'GAClient' (4136672064)
[00:00:00]: CurlRequestManager::ClientThread::Main()
[00:00:00]: ProfileIndex:8.41
[00:00:00]: [Connect] PendingConnection::Reset(true)
[00:00:00]: Network tick rate: U=15(2), D=0
[00:00:00]: Network tick rate: U=15(2), D=0
[00:00:00]: Error trying to change cluster setting (NETWORK->cluster_intention) from '' to 'cooperative'
[00:00:00]: OnLoadPermissionList: /var/lib/dsta//./cluster/blocklist.txt (Failure)
[00:00:00]: THREAD - started 'ConsoleInput' (4129291072)
[00:00:00]: OnLoadPermissionList: /var/lib/dsta//./cluster/adminlist.txt (Failure)
[00:00:00]: OnLoadUserIdList: /var/lib/dsta//./cluster/whitelist.txt (Failure)
[00:00:00]: Token retrieved from: /var/lib/dsta//./cluster/cluster_token.txt
[00:00:00]: Token retrieved from: /var/lib/dsta//./cluster/cluster_token.txt
[00:00:00]: cGame::InitializeOnMainThread
[00:00:00]: Renderer initialize: Okay
[00:00:00]: AnimManager initialize: Okay
[00:00:00]: Buffers initialize: Okay
[00:00:00]: cDontStarveGame::DoGameSpecificInitialize()
[00:00:00]: FMOD Error: An invalid object handle was used. 
[00:00:00]: GameSpecific initialize: Okay
[00:00:00]: cGame::StartPlaying
[00:00:00]: LOADING LUA
[00:00:00]: DoLuaFile scripts/main.lua
[00:00:00]: DoLuaFile loading buffer scripts/main.lua
[00:00:00]: running main.lua
	
[00:00:00]: Could not load modindex	
[00:00:00]: ModIndex: Beginning normal load sequence for dedicated server.
	
[00:00:00]: DownloadMods(0)
[00:00:00]: FMOD Error: An invalid object handle was used. 
[00:00:00]: LOADING LUA SUCCESS
[00:00:00]: PlayerDeaths could not load morgue	
[00:00:00]: PlayerHistory could not load player_history	
[00:00:00]: bloom_enabled	false	
[00:00:00]: Could not load saveindex	
[00:00:00]: OnFilesLoaded()	
[00:00:00]: OnUpdatePurchaseStateComplete	
[00:00:01]: 	Load FE	
[00:00:01]: 	Load FE: done	
[00:00:01]: ModIndex: Load sequence finished successfully.	
[00:00:01]: Reset() returning
[00:00:02]: [200] Account Communication Success (6)
[00:00:02]: Received (KU_GWmhvzEo) from TokenPurpose
[00:00:02]: Starting Dedicated Server Game	
[00:00:02]: Network tick rate: U=15(2), D=0
[00:00:02]: About to start a server with the following settings:
[00:00:02]:   Dedicated: true
[00:00:02]:   Online: true
[00:00:02]:   Passworded: false
[00:00:02]:   ServerPort: 10999
[00:00:02]:   SteamAuthPort: 8766
[00:00:02]:   SteamMasterServerPort: 27016
[00:00:02]:   ClanID: false
[00:00:02]:   ClanOnly: false
[00:00:02]:   ClanAdmin: false
[00:00:02]:   LanOnly: false
[00:00:02]:   FriendsOnly: false
[00:00:02]:   EnableAutosaver: true
[00:00:02]:   PVP: false
[00:00:02]:   MaxPlayers: 4
[00:00:02]:   GameMode: survival
[00:00:02]:   OverridenDNS: 
[00:00:02]:   PauseWhenEmpty: true
[00:00:02]:   VoteEnabled: true
[00:00:02]:   InternetBroadcasting: true
[00:00:02]:   Intent: cooperative
[00:00:02]: [Shard] Shard server mode disabled by configuration file
[00:00:02]: Online Server Started on port: 10999
[00:00:02]: Not applying level data overrides.	
[00:00:02]: Not applying world gen overrides.	
[00:00:02]: Collecting garbage...
[00:00:02]: lua_gc took 0.02 seconds
[00:00:02]: ~ShardLuaProxy()
[00:00:02]: ~ItemServerLuaProxy()
[00:00:02]: ~InventoryLuaProxy()
[00:00:02]: ~NetworkLuaProxy()
[00:00:02]: ~SimLuaProxy()
[00:00:02]: lua_close took 0.02 seconds
[00:00:02]: ReleaseAll
[00:00:02]: ReleaseAll Finished
[00:00:02]: cGame::StartPlaying
[00:00:02]: LOADING LUA
[00:00:02]: DoLuaFile scripts/main.lua
[00:00:02]: DoLuaFile loading buffer scripts/main.lua
[00:00:02]: running main.lua
	
[00:00:02]: loaded modindex	
[00:00:02]: ModIndex: Beginning normal load sequence for dedicated server.
	
[00:00:02]: LOADING LUA SUCCESS
[00:00:02]: PlayerDeaths could not load morgue	
[00:00:02]: PlayerHistory could not load player_history	
[00:00:02]: bloom_enabled	false	
[00:00:02]: OnLoad slot	2	: World options was nil! Populating with default.	
[00:00:02]: OnLoad slot	3	: World options was nil! Populating with default.	
[00:00:02]: OnLoad slot	4	: World options was nil! Populating with default.	
[00:00:02]: OnLoad slot	5	: World options was nil! Populating with default.	
[00:00:02]: loaded saveindex	
[00:00:02]: OnFilesLoaded()	
[00:00:02]: OnUpdatePurchaseStateComplete	
[00:00:02]: Load Slot: ... generating new world	
[00:00:02]: WorldSim::SimThread::SimThread()
[00:00:02]: ABOUT TO INSTALL STACKTRACE
[00:00:02]: DoLuaFile scripts/stacktrace.lua
[00:00:02]: DoLuaFile loading buffer scripts/stacktrace.lua
[00:00:02]: INSTALLED STACKTRACE
[00:00:02]: WorldSim::SimThread::SimThread() complete
[00:00:02]: THREAD - started 'WorldSim' (4054842176)
[00:00:02]: WorldSim::SimThread::Main()
[00:00:02]: DoLuaFile scripts/worldgen_main.lua
[00:00:02]: DoLuaFile loading buffer scripts/worldgen_main.lua
[00:00:02]: DLC enabled : 	false	
[00:00:02]: ModIndex: Load sequence finished successfully.	
[00:00:02]: Reset() returning
[00:00:02]: running worldgen_main.lua
	
[00:00:02]: SEED = 	1477988495	
[00:00:02]: Generating world with these parameters:	
[00:00:02]: level_type	SURVIVAL	
[00:00:02]: level_data:	
[00:00:02]: 	K: 	1	 V: 	table: 0xf125d290	
[00:00:02]: 		K: 	desc	 V: 	The standard Don't Starve experience.	
[00:00:02]: 		K: 	hideminimap	 V: 	false	
[00:00:02]: 		K: 	id	 V: 	SURVIVAL_TOGETHER	
[00:00:02]: 		K: 	location	 V: 	forest	
[00:00:02]: 		K: 	max_playlist_position	 V: 	999	
[00:00:02]: 		K: 	min_playlist_position	 V: 	0	
[00:00:02]: 		K: 	name	 V: 	Default	
[00:00:02]: 		K: 	numrandom_set_pieces	 V: 	4	
[00:00:02]: 		K: 	ordered_story_setpieces	 V: 	table: 0xf125d2b8	
[00:00:02]: 			K: 	1	 V: 	Sculptures_1	
[00:00:02]: 			K: 	2	 V: 	Maxwell5	
[00:00:02]: 		K: 	override_level_string	 V: 	false	
[00:00:02]: 		K: 	overrides	 V: 	table: 0xf125fef0	
[00:00:02]: 			K: 	layout_mode	 V: 	LinkNodesByKeys	
[00:00:02]: 			K: 	roads	 V: 	default	
[00:00:02]: 			K: 	season_start	 V: 	default	
[00:00:02]: 			K: 	start_location	 V: 	default	
[00:00:02]: 			K: 	task_set	 V: 	default	
[00:00:02]: 			K: 	world_size	 V: 	default	
[00:00:02]: 			K: 	wormhole_prefab	 V: 	wormhole	
[00:00:02]: 		K: 	random_set_pieces	 V: 	table: 0xf125ddc0	
[00:00:02]: 			K: 	1	 V: 	Sculptures_2	
[00:00:02]: 			K: 	2	 V: 	Sculptures_3	
[00:00:02]: 			K: 	3	 V: 	Sculptures_4	
[00:00:02]: 			K: 	4	 V: 	Sculptures_5	
[00:00:02]: 			K: 	5	 V: 	Chessy_1	
[00:00:02]: 			K: 	6	 V: 	Chessy_2	
[00:00:02]: 			K: 	7	 V: 	Chessy_3	
[00:00:02]: 			K: 	8	 V: 	Chessy_4	
[00:00:02]: 			K: 	9	 V: 	Chessy_5	
[00:00:02]: 			K: 	10	 V: 	Chessy_6	
[00:00:02]: 			K: 	11	 V: 	Maxwell1	
[00:00:02]: 			K: 	12	 V: 	Maxwell2	
[00:00:02]: 			K: 	13	 V: 	Maxwell3	
[00:00:02]: 			K: 	14	 V: 	Maxwell4	
[00:00:02]: 			K: 	15	 V: 	Maxwell6	
[00:00:02]: 			K: 	16	 V: 	Maxwell7	
[00:00:02]: 			K: 	17	 V: 	Warzone_1	
[00:00:02]: 			K: 	18	 V: 	Warzone_2	
[00:00:02]: 			K: 	19	 V: 	Warzone_3	
[00:00:02]: 		K: 	required_prefabs	 V: 	table: 0xf125d3e0	
[00:00:02]: 			K: 	1	 V: 	multiplayer_portal	
[00:00:02]: 		K: 	substitutes	 V: 	table: 0xf125f6e0	
[00:00:02]: 		K: 	version	 V: 	3	
[00:00:02]: 
#######
#
# Generating SURVIVAL Mode Level
#
#######
	
[00:00:02]: Prefab Swap Selection: regular grass	
[00:00:02]: Prefab Swap Selection: regular twigs	
[00:00:02]: Prefab Swap Selection: regular berries	
[00:00:02]: Maxwell3	added to	For a nice walk	
[00:00:02]: Chessy_2	added to	Speak to the king	
[00:00:02]: Maxwell2	added to	Magic meadow	
[00:00:02]: Maxwell4	added to	Killer bees!	
[00:00:02]: New size:	425	default	
[00:00:02]: Creating story...	
[00:00:02]: LinkNodesByKeys	
[00:00:02]: Finding valid start task...	
[00:00:02]:    ...picked 	Make a pick	
[00:00:02]: Has start node	Clearing	
[00:00:02]: Baking map...	425	
[00:00:02]: [WorldSimActual::GenerateVoronoiMap]
[00:00:02]: GenerateVoronoiMap [1]:
[00:00:02]: ...Done.
[00:00:02]: [AddEmptyNodes]
[00:00:02]: GenerateVoronoiMap [100]:
[00:00:03]: ...Done.
[00:00:03]: [WorldSimActual::GenerateVoronoiMap] complete [success]
[00:00:03]: [WorldSimActual::ConvertToTileMap]
[00:00:03]: [ConvertToTileMap]
[00:00:03]: [WorldSimActual::ConvertToTileMap] complete
[00:00:03]: [WorldSimActual::SeparateIslands]
[00:00:03]: [SeparateIslands]
[00:00:03]: [WorldSimActual::SeparateIslands] complete
[00:00:03]: Map Baked!	
[00:00:03]: [WorldSimActual::ForceConnectivity]
[00:00:03]: [GenerateLandmasses]
[00:00:03]: [MergeConnectedLandmasses] true
[00:00:03]: [WorldSimActual::ForceConnectivity] complete
[00:00:03]: [GetWormholesExtra] connected 0 unconnected 1
[00:00:03]: [GetWormholesExtra] after: connected 1 unconnected 0
[00:00:03]: [GetWormholesExtra] pushed 0 wormholes
[00:00:03]: [WorldSimActual::DrawRoads]
[00:00:03]: [DrawRoads]
[00:00:03]: [WorldSimActual::DrawRoads] complete
[00:00:03]: Encoding...	
[00:00:03]: Encoding... DONE	
[00:00:03]: Checking Tags	
[00:00:03]: Populating voronoi...	
[00:00:03]: Warning! Could not find a spot for Maxwell2 in node Magic meadow:BG_17:Clearing	
[00:00:03]: disconnected tiles...	0	
[00:00:03]: Done forest map gen!	
[00:00:03]: Checking map...	
[00:00:03]: Generation complete	
[00:00:03]: WorldSim::SimThread::Main() complete
[00:00:03]: Serializing world: session/C567D93603547EEE/0000000002
[00:00:03]: 	Unload FE	
[00:00:03]: 	Unload FE done	
[00:00:04]: 	LOAD BE	
[00:00:05]: 	LOAD BE: done	
[00:00:05]: Begin Session: C567D93603547EEE
[00:00:05]: saving to server_temp/server_save	
[00:00:05]: MiniMapComponent::AddAtlas( minimap/minimap_data.xml )
[00:00:05]: Loading Nav Grid	
[00:00:09]: Reconstructing topology	
[00:00:09]: 	...Sorting points	
[00:00:09]: 	...Sorting edges	
[00:00:09]: 	...Connecting nodes	
[00:00:09]: 	...Validating connections	
[00:00:09]: 	...Housekeeping	
[00:00:09]: 	...Done!	
[00:00:09]: Halloween Trinkets added: 59	
[00:00:09]: 1 uploads added to server. From server_temp
[00:00:09]: Telling Client our new session identifier: C567D93603547EEE
[00:00:09]: [Steam] SteamGameServer_Init(8766, 10999, 27016)
[00:00:09]: [Steam] SteamGameServer_Init success
[00:00:10]: Validating portal[1] <-> <nil>[1] (inactive)	
[00:00:10]: Validating portal[2] <-> <nil>[2] (inactive)	
[00:00:10]: Validating portal[3] <-> <nil>[3] (inactive)	
[00:00:10]: Validating portal[4] <-> <nil>[4] (inactive)	
[00:00:10]: Validating portal[5] <-> <nil>[5] (inactive)	
[00:00:10]: Validating portal[6] <-> <nil>[6] (inactive)	
[00:00:10]: Validating portal[7] <-> <nil>[7] (inactive)	
[00:00:10]: Validating portal[8] <-> <nil>[8] (inactive)	
[00:00:10]: Validating portal[9] <-> <nil>[9] (inactive)	
[00:00:10]: Validating portal[10] <-> <nil>[10] (inactive)	
[00:00:10]: Sim paused
```

**Comment by thasmo** [comment]
Thanks for reporting! :+1: I'm on it.

**Comment by thasmo** [comment]
The actual problem is that our image creates all the configuration files for the server, including the file `dedicated_server_mods_setup.lua` which gets overwritten afterwards, if a game-update is available.

In detail; we actually run `build/static/boot/mods.sh` which creates the mod-configuration, and afterwards we run `build/static/dst/update.sh`, which installs a new game-version, if available, which overwrites the `dedicated_server_mods_setup.lua` file again.

I believe we should move most of the logic in `build/docker-entrypoint.sh` to `build/static/bin/start.sh`, to ensure a consistent creation of all configuration files.

**Comment by thasmo** [comment]
This has been fixed and will be released with version 0.7. Thanks again for reporting!

**Comment by ghost** [comment]
Still not working with current origin/develop branch. Again I'm using exactly the same files like in the docs/examples/mods/ directory. Maybe it's related to https://github.com/dst-academy/docker-dontstarvetogether/pull/70?

```
world    | 0]: PersistRootStorage is now /var/lib/dsta//./cluster/shard/
world    | [00:00:00]: Starting Up
world    | [00:00:00]: Version: 194420
world    | [00:00:00]: Current time: Thu Nov  3 09:00:31 2016
world    |
world    | [00:00:00]: System Name: Linux
world    | [00:00:00]: Host Name: world
world    | [00:00:00]: Release(Kernel) Version: 4.4.0-36-generic
world    | [00:00:00]: Kernel Build Timestamp: #55-Ubuntu SMP Thu Aug 11 18:01:55 UTC 2016
world    | [00:00:00]: Machine Arch: x86_64
world    | [00:00:00]: Don't Starve Together: 194420 LINUX
world    | [00:00:00]: Build Date: 1378
world    | [00:00:00]: Parsing command line
world    | [00:00:00]: Command Line Arguments: -persistent_storage_root /var/lib/dsta -conf_dir . -cluster cluster -shard shard -backup_log_count 0 -skip_update_server_mods
world    | [00:00:00]: Initializing distribution platform
world    | [00:00:00]: ....Done
world    | [00:00:00]: THREAD - started 'GAClient' (4137093952)
world    | [00:00:00]: CurlRequestManager::ClientThread::Main()
world    | [00:00:00]: ProfileIndex:4.00
world    | [00:00:00]: [Connect] PendingConnection::Reset(true)
world    | [00:00:00]: Network tick rate: U=15(2), D=0
world    | [00:00:00]: Network tick rate: U=15(2), D=0
world    | [00:00:00]: Error trying to change cluster setting (NETWORK->cluster_intention) from '' to 'cooperative'
world    | [00:00:00]: THREAD - started 'ConsoleInput' (4130339648)
world    | [00:00:00]: OnLoadPermissionList: /var/lib/dsta//./cluster/blocklist.txt (Failure)
world    | [00:00:00]: OnLoadPermissionList: /var/lib/dsta//./cluster/adminlist.txt (Failure)
world    | [00:00:00]: OnLoadUserIdList: /var/lib/dsta//./cluster/whitelist.txt (Failure)
world    | [00:00:00]: Token retrieved from: /var/lib/dsta//./cluster/cluster_token.txt
world    | [00:00:00]: Token retrieved from: /var/lib/dsta//./cluster/cluster_token.txt
world    | [00:00:00]: cGame::InitializeOnMainThread
world    | [00:00:00]: Renderer initialize: Okay
world    | [00:00:00]: AnimManager initialize: Okay
world    | [00:00:00]: Buffers initialize: Okay
world    | [00:00:00]: cDontStarveGame::DoGameSpecificInitialize()
world    | [00:00:00]: FMOD Error: An invalid object handle was used.
world    | [00:00:00]: GameSpecific initialize: Okay
world    | [00:00:00]: cGame::StartPlaying
world    | [00:00:00]: LOADING LUA
world    | [00:00:00]: DoLuaFile scripts/main.lua
world    | [00:00:00]: DoLuaFile loading buffer scripts/main.lua
world    | [00:00:00]: running main.lua
world    |
world    | [00:00:00]: Could not load modindex
world    | [00:00:00]: ModIndex: Beginning normal load sequence for dedicated server.
world    |
world    | [00:00:00]: FMOD Error: An invalid object handle was used.
world    | 1]: LOADING LUA SUCCESS
world    | 1]: PlayerDeaths could not load morgue
world    | [00:00:01]: PlayerHistory could not load player_history
world    | 1]: bloom_enabled    false
world    | 1]: Could not load saveindex
world    | [00:00:01]: OnFilesLoaded()
world    | [00:00:01]: OnUpdatePurchaseStateComplete
world    | 1]:  Load FE
world    | 1]:  Load FE: done
world    | 1]: ModIndex: Load sequence finished successfully.
world    | [00:00:01]: Reset() returning
world    | 2]: [200] Account Communication Success (6)
world    | [00:00:02]: Received (KU_GWmhvzEo) from TokenPurpose
world    | [00:00:02]: Starting Dedicated Server Game
world    | [00:00:02]: Network tick rate: U=15(2), D=0
world    | 2]: About to start a server with the following settings:
world    | [00:00:02]:   Dedicated: true
world    | [00:00:02]:   Online: true
world    | [00:00:02]:   Passworded: false
world    | [00:00:02]:   ServerPort: 10999
world    | [00:00:02]:   SteamAuthPort: 8766
world    | [00:00:02]:   SteamMasterServerPort: 27016
world    | [00:00:02]:   ClanID: false
world    | [00:00:02]:   ClanOnly: false
world    | [00:00:02]:   ClanAdmin: false
world    | [00:00:02]:   LanOnly: false
world    | [00:00:02]:   FriendsOnly: false
world    | [00:00:02]:   EnableAutosaver: true
world    | [00:00:02]:   PVP: false
world    | [00:00:02]:   MaxPlayers: 4
world    | [00:00:02]:   GameMode: survival
world    | [00:00:02]:   OverridenDNS:
world    | [00:00:02]:   PauseWhenEmpty: true
world    | [00:00:02]:   VoteEnabled: true
world    | [00:00:02]:   InternetBroadcasting: true
world    | [00:00:02]:   Intent: cooperative
world    | [00:00:02]: [Shard] Shard server mode disabled by configuration file
world    | 2]: Online Server Started on port: 10999
world    | 2]: Not applying level data overrides.
world    | [00:00:02]: Not applying world gen overrides.
world    | 2]: Collecting garbage...
world    | 2]: lua_gc took 0.01 seconds
world    | [00:00:02]: ~ShardLuaProxy()
world    | [00:00:02]: ~ItemServerLuaProxy()
world    | [00:00:02]: ~InventoryLuaProxy()
world    | [00:00:02]: ~NetworkLuaProxy()
world    | [00:00:02]: ~SimLuaProxy()
world    | 2]: lua_close took 0.02 seconds
world    | 2]: ReleaseAll
world    | [00:00:02]: ReleaseAll Finished
world    | [00:00:02]: cGame::StartPlaying
world    | 2]: LOADING LUA
world    | [00:00:02]: DoLuaFile scripts/main.lua
world    | [00:00:02]: DoLuaFile loading buffer scripts/main.lua
world    | 2]: running main.lua
world    |
world    | 2]: loaded modindex
world    | [00:00:02]: ModIndex: Beginning normal load sequence for dedicated server.
world    |
world    | 2]: LOADING LUA SUCCESS
world    | 2]: PlayerDeaths could not load morgue
world    | [00:00:02]: PlayerHistory could not load player_history
world    | 2]: bloom_enabled    false
world    | 2]: OnLoad slot      2       : World options was nil! Populating with default.
world    | [00:00:02]: OnLoad slot      3       : World options was nil! Populating with default.
world    | 2]: OnLoad slot      4       : World options was nil! Populating with default.
world    | [00:00:02]: OnLoad slot      5       : World options was nil! Populating with default.
world    | 2]: loaded saveindex
world    | [00:00:02]: OnFilesLoaded()
world    | [00:00:02]: OnUpdatePurchaseStateComplete
world    | [00:00:02]: Load Slot: ... generating new world
world    | 2]: WorldSim::SimThread::SimThread()
world    | [00:00:02]: ABOUT TO INSTALL STACKTRACE
world    | [00:00:02]: DoLuaFile scripts/stacktrace.lua
world    | [00:00:02]: DoLuaFile loading buffer scripts/stacktrace.lua
world    | 2]: INSTALLED STACKTRACE
world    | [00:00:02]: WorldSim::SimThread::SimThread() complete
world    | [00:00:02]: THREAD - started 'WorldSim' (4054842176)
world    | [00:00:02]: WorldSim::SimThread::Main()
world    | [00:00:02]: DoLuaFile scripts/worldgen_main.lua
world    | 2]: DoLuaFile loading buffer scripts/worldgen_main.lua
world    | 2]: ModIndex: Load sequence finished successfully.
world    | [00:00:02]: Reset() returning
world    | 2]: DLC enabled :    false
world    | 2]: running worldgen_main.lua
world    |
world    | [00:00:02]: SEED =   1478163633
world    | 2]: Generating world with these parameters:
world    | [00:00:02]: level_type       SURVIVAL
world    | [00:00:02]: level_data:
world    | [00:00:02]:  K:      1        V:     table: 0xf125d130
world    | [00:00:02]:          K:      desc     V:     The standard Don't Starve experience.
world    | 2]:          K:      hideminimap      V:     false
world    | [00:00:02]:          K:      id       V:     SURVIVAL_TOGETHER
world    | [00:00:02]:          K:      location         V:     forest
world    | [00:00:02]:          K:      max_playlist_position    V:     999
world    | [00:00:02]:          K:      min_playlist_position    V:     0
world    | [00:00:02]:          K:      name     V:     Default
world    | [00:00:02]:          K:      numrandom_set_pieces     V:     4
world    | [00:00:02]:          K:      ordered_story_setpieces  V:     table: 0xf125d158
world    | [00:00:02]:                  K:      1        V:     Sculptures_1
world    | [00:00:02]:                  K:      2        V:     Maxwell5
world    | [00:00:02]:          K:      override_level_string    V:     false
world    | [00:00:02]:          K:      overrides        V:     table: 0xf125fd68
world    | [00:00:02]:                  K:      layout_mode      V:     LinkNodesByKeys
world    | [00:00:02]:                  K:      roads    V:     default
world    | [00:00:02]:                  K:      season_start     V:     default
world    | [00:00:02]:                  K:      start_location   V:     default
world    | [00:00:02]:                  K:      task_set         V:     default
world    | [00:00:02]:                  K:      world_size       V:     default
world    | [00:00:02]:                  K:      wormhole_prefab  V:     wormhole
world    | [00:00:02]:          K:      random_set_pieces        V:     table: 0xf125dc58
world    | 2]:                  K:      1        V:     Sculptures_2
world    | [00:00:02]:                  K:      2        V:     Sculptures_3
world    | [00:00:02]:                  K:      3        V:     Sculptures_4
world    | [00:00:02]:                  K:      4        V:     Sculptures_5
world    | [00:00:02]:                  K:      5        V:     Chessy_1
world    | [00:00:02]:                  K:      6        V:     Chessy_2
world    | [00:00:02]:                  K:      7        V:     Chessy_3
world    | [00:00:02]:                  K:      8        V:     Chessy_4
world    | [00:00:02]:                  K:      9        V:     Chessy_5
world    | [00:00:02]:                  K:      10       V:     Chessy_6
world    | [00:00:02]:                  K:      11       V:     Maxwell1
world    | [00:00:02]:                  K:      12       V:     Maxwell2
world    | [00:00:02]:                  K:      13       V:     Maxwell3
world    | [00:00:02]:                  K:      14       V:     Maxwell4
world    | [00:00:02]:                  K:      15       V:     Maxwell6
world    | [00:00:02]:                  K:      16       V:     Maxwell7
world    | [00:00:02]:                  K:      17       V:     Warzone_1
world    | [00:00:02]:                  K:      18       V:     Warzone_2
world    | [00:00:02]:                  K:      19       V:     Warzone_3
world    | [00:00:02]:          K:      required_prefabs         V:     table: 0xf125d298
world    | [00:00:02]:                  K:      1        V:     multiplayer_portal
world    | [00:00:02]:          K:      substitutes      V:     table: 0xf125f558
world    | [00:00:02]:          K:      version  V:     3
world    | [00:00:02]:
world    | #######
world    | #
world    | # Generating SURVIVAL Mode Level
world    | #
world    | #######
world    |
world    | [00:00:02]: Prefab Swap Selection: grass gekko
world    | [00:00:02]: Prefab Swap Selection: regular twigs
world    | 2]: Prefab Swap Selection: regular berries
world    | 2]: Maxwell2 added to        Make a pick
world    | [00:00:02]: Warzone_2        added to        Mole Colony Rocks
world    | [00:00:02]: Chessy_3 added to        Speak to the king
world    | [00:00:02]: Warzone_3        added to        Squeltch
world    | 2]: New size:        425     default
world    | [00:00:02]: Creating story...
world    | 2]: LinkNodesByKeys
world    | 2]: Finding valid start task...
world    | [00:00:02]:    ...picked     Make a pick
world    | [00:00:02]: Has start node   Clearing
world    | 2]: Baking map...    425
world    | [00:00:02]: [WorldSimActual::GenerateVoronoiMap]
world    | [00:00:02]: GenerateVoronoiMap [1]:
world    | 0:02]: ...Done.
world    | 2]: [AddEmptyNodes]
world    | 2]: GenerateVoronoiMap [100]:
world    | ...20....30....40....50....60....70....80....90....100
world    | [00:00:04]: ...Done.
world    | 4]: [WorldSimActual::GenerateVoronoiMap] complete [success]
world    | 4]: [WorldSimActual::ConvertToTileMap]
world    | 4]: [ConvertToTileMap]
world    | 4]: [WorldSimActual::ConvertToTileMap] complete
world    | [00:00:04]: [WorldSimActual::SeparateIslands]
world    | [00:00:04]: [SeparateIslands]
world    | 4]: [WorldSimActual::SeparateIslands] complete
world    | [00:00:04]: Map Baked!
world    | [00:00:04]: [WorldSimActual::ForceConnectivity]
world    | [00:00:04]: [GenerateLandmasses]
world    | 4]: [MergeConnectedLandmasses] true
world    | 4]: [WorldSimActual::ForceConnectivity] complete
world    | [00:00:04]: [GetWormholesExtra] connected 0 unconnected 1
world    | [00:00:04]: [GetWormholesExtra] after: connected 1 unconnected 0
world    | [00:00:04]: [GetWormholesExtra] pushed 0 wormholes
world    | [00:00:04]: [WorldSimActual::DrawRoads]
world    | [00:00:04]: [DrawRoads]
world    | 4]: [WorldSimActual::DrawRoads] complete
world    | 4]: Encoding...
world    | 4]: Encoding... DONE
world    | 4]: Checking Tags
world    | 4]: Populating voronoi...
world    | 4]: Warning! Could not find a spot for Maxwell2 in node Make a pick:5:Plain
world    | 4]: disconnected tiles...    0
world    | 4]: Done forest map gen!
world    | [00:00:04]: Checking map...
world    | [00:00:04]: Generation complete
world    | 4]: WorldSim::SimThread::Main() complete
world    | 4]: Serializing world: session/9F5D45DBCA6B1372/0000000002
world    | 4]:  Unload FE
world    | 4]:  Unload FE done
world    | 5]:  LOAD BE
world    | 6]:  LOAD BE: done
world    | 6]: Begin Session: 9F5D45DBCA6B1372
world    | 6]: saving to server_temp/server_save
world    | 6]: MiniMapComponent::AddAtlas( minimap/minimap_data.xml )
world    | 6]: Loading Nav Grid
world    | 9]: Reconstructing topology
world    | [00:00:09]:  ...Sorting points
world    | 9]:  ...Sorting edges
world    | 9]:  ...Connecting nodes
world    | 9]:  ...Validating connections
world    | 9]:  ...Housekeeping
world    | 9]:  ...Done!
world    | 9]: Halloween Trinkets added: 77
world    | 9]: 1 uploads added to server. From server_temp
world    | [00:00:09]: Telling Client our new session identifier: 9F5D45DBCA6B1372
world    | 9]: [Steam] SteamGameServer_Init(8766, 10999, 27016)
world    | [S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
world    | breakpad minidump AppID = 322330
world    | [00:00:09]: [Steam] SteamGameServer_Init success
world    | 9]: Validating portal[1] <-> <nil>[1] (inactive)
world    | 9]: Validating portal[2] <-> <nil>[2] (inactive)
world    | 9]: Validating portal[3] <-> <nil>[3] (inactive)
world    | [00:00:09]: Validating portal[4] <-> <nil>[4] (inactive)
world    | [00:00:09]: Validating portal[5] <-> <nil>[5] (inactive)
world    | [00:00:09]: Validating portal[6] <-> <nil>[6] (inactive)
world    | 0]: Validating portal[7] <-> <nil>[7] (inactive)
world    | 0]: Validating portal[8] <-> <nil>[8] (inactive)
world    | 0]: Validating portal[9] <-> <nil>[9] (inactive)
world    | 0]: Validating portal[10] <-> <nil>[10] (inactive)
world    | 0]: Sim paused
```

**Comment by thasmo** [comment]
@ColorizedMind For now you need to adapt the `docker-compose.yml` file a bit to get the current development version of the image. Try to use this `docker-compose.yml` file and be sure to start your Docker container by using the provided `start.sh` file in the directory.

``` yml
version: "2"
services:
  world:
    image: dstacademy/dontstarvetogether:next
    container_name: world
    hostname: world
    tty: true
    stdin_open: true
    env_file: world.env
    command: --update=all
    ports:
      - "10999:10999/udp"
    volumes:
      - ./world:/var/lib/dsta/cluster
```

Please report back if this works for you consistently. Thanks!

**Comment by Zenuncl** [comment]
I have similar issue:
- I just pull the latest image, seem like the latest version which include the 0.7 changes (let me know if it's wrong
- the `command --update=all` is in compose file
- Similar logs, seem like mods downloaded and set up (no error message), but when i load game, there is nothing. The server list also shows that game does not have mods

**Comment by thasmo** [comment]
@SharkIng Would you mind sharing your setup? Thanks!

**Comment by Zenuncl** [comment]
```
# MODS
MODS=378160973,492173795,407705132,376333686,345692228,459280938
MODS_OVERRIDES
```

```
return {
	['workshop-378160973'] = { enabled = true },
	['workshop-492173795'] = { enabled = true },
	['workshop-407705132'] = { enabled = true,
		configuration_options = {
			title = 'Welcome To DST!',
			message = 'This is a private DST server!',
		},
	},
	['workshop-376333686'] = { enabled = true },
	['workshop-345692228'] = { enabled = true },
	['workshop-459280938'] = { enabled = true },
}
```

The most config are default and/or copy-paste from [example](https://github.com/dst-academy/docker-dontstarvetogether/tree/develop/docs/examples/mods).
I am still debugging and I may need rebuild entire server for a clean installation. I'll let you know when I found anything useful.

And something for other users:
- DS mods are not working, and some DST mods seem like not configurable.
- Some mods not working at ALL (Maybe) and remove it may solve problem
- Edit configuration seem like need clean build/launch new DST docker.(?)

**Comment by thasmo** [comment]
Tried it and in my case the server installs the mods, although not all mods are showing up.
